apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: k8s-net-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-net-pod
  template:
    metadata:
      labels:
        app: k8s-net-pod
    spec:
      containers:
        - name: k8s-net-replicaset
          image: k8sdemo
          imagePullPolicy: IfNotPresent
